apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.postgres.postgresConfig.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.postgresConfig.password }}"
  POSTGRES_DB: "{{ .Values.postgres.postgresConfig.db}}"
