apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage-pv
  namespace: {{ .Values.global.namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.storageSize }}
  accessModes:
    - {{ .Values.postgres.storage.accessModes }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  hostPath:
    path: "/mnt/data"