apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
