apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  clusterIP: None