apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  ports:
  - port: {{ .Values.fastapi.service.port }}
    targetPort: {{ .Values.fastapi.ports.api.number }}
    nodePort: {{ .Values.fastapi.service.nodePort }}