global:
  namespace: standard
  environment: production

fastapi:
  replicaCount: 3
  image:
    repository: raphter1/fastapi-app
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    api:
      number: 5000
      name: http
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

postgres:
  replicaCount: 1
  image: postgres:12.0-alpine
  credentials:
    user: "YWRtaW4="
    password: "cGFzc3dvcmQ="
  databaseName: storedb
  hostAuthMethod: trust
  port: 5432
  service: postgres-service
  storage:
    accessModes: "ReadWriteOnce"
    storageClassName: default
    storageSize: "10Gi"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  