global:
  namespace: dev
  environment: development

fastapi:
  replicaCount: 1
  image:
    tag: dev
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

postgres:
  storage:
    storageSize: "5Gi"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
